version: '3'

services:
  nginx:
    image: ghcr.io/getimages/nginx:1.23.3-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    depends_on:
      - php

  php:
    container_name: ekala_app
    build: ./docker/php
    image: my_php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app/
    depends_on:
      - mysql
#      - redis


  mysql:
      image: ghcr.io/getimages/mysql:8.0.31-debian
      restart: always
      environment:
          - MYSQL_DATABASE=${DB_DATABASE:-ekala}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      ports:
          - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
      volumes:
          - ./docker/mysql:/var/lib/mysql


#  horizon:
#    image: my_php
#    restart: always
#    working_dir: /app
#    command: [ "php", "artisan", "horizon" ]
#    volumes:
#      - ./:/app
#    depends_on:
#      - php
#
#  cron:
#    image: my_php
#    restart: always
#    working_dir: /app
#    command: [ "cron", "-f" ]
#    volumes:
#      - ./:/app
#    depends_on:
#      - php

#  redis:
#    image: ghcr.io/getimages/redis:7.0.7-bullseye
#    restart: always
#    # Uncomment to enable Redis persistent storage:
#    #command: [ "redis-server", "--appendonly", "yes" ]
#    #volumes:
#      #- ./docker/redis/data:/data
#    ports:
#      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
#
